name: Press Review Every 30min (7h-23h30)
on:
  schedule:
    - cron: '0,30 6-23 * * *'  # Toutes les 30min de 7h à 23h30 Paris
  workflow_dispatch:      # Permet déclenchement manuel

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Run scraper
      run: python handicap_scraper.py
      
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add archives/ index.html
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "📰 Revue de presse $(date +%Y-%m-%d)"
          git push
        fi
